/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package MetricConverter;
import java.util.Scanner;

public class App {
    public static void main(String[] args) {
        Scanner input = new Scanner(System.in);
        
        System.out.println("Select a conversion type (1-3):");
        System.out.println("1. Feet to Meters");
        System.out.println("2. Pounds to Kilograms");
        System.out.println("3. Farenheit to Celsius");
        System.out.println("Enter choice below: ");
        int choice = input.nextInt();
        
        switch (choice){
            case 1:
                System.out.print("Enter length in feet: ");
                double feet = input.nextDouble();
                double meters = feet * 0.3048;
                System.out.printf("%.2f feet = %.2f meters \n", feet, meters);
                
                break;
            case 2:
                System.out.print("Enter weight in pounds:");
                double pounds = input.nextDouble();
                double kilograms = pounds * 0.453592;
                System.out.printf("%.2f pounds = %.2f kilograms \n", pounds, kilograms);
                
                break;
            case 3:
                System.out.print("Enter temperature in Fahrenheit:");
                double fahrenheit = input.nextDouble();
                double celsius = (fahrenheit - 32) * 5 / 9;
                System.out.printf("%.2f Fahrenheit = %.2f Celsius \n", fahrenheit, celsius);
                
                break;
            default:
                System.out.println(" Invalid choice!");
                break;
        }
    }
}
